name: Build and Deploy exe

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install cython pyinstaller
          
      - name: Install Python development package
        # For "Python.h"
        run: |
          winget install --id Python.DevelopmentKit
          
      - name: Compile Cython code
        run: |
          cython spatial.py
          gcc -shared -O2 spatial.c -o spatial.pyd

      - name: Build executable
        run: |
          pyinstaller --windowed --onefile --name Spatial spatial.pyd

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Spatial.exe
          path: dist/Spatial.exe
