name: Build and Deploy exe

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r requirements-windows.txt
          pip install pyinstaller
          pip install nuitka

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --windowed --name Spatial spatial.py

      - name: Build executable with Nuitka
        run: |
          nuitka --standalone --windows-console-mode=disable --output-dir=dist/nuitka --verbose Spatial.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Spatial
          path: |
            dist/*  # PyInstaller output
            dist/nuitka/*  # Nuitka output
