name: Pylint

# on: [push]
on: []

jobs:
  build:
    runs-on: windows-latest  # Use windows-latest for Windows 10 and 11 support
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2  # Update to v2 for better Windows support
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt  # Make sure requirements.txt is in your repository
    - name: Analysing the code with pylint
      run: |
        pylint $(Get-ChildItem -Path . -Filter "*.py" -Recurse | Select-Object -ExpandProperty FullName)
