name: Windows Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        shell: cmd
        # %LOCALAPPDATA%\Microsoft\WindowsApps\python3.exe
        run: |
          echo Setting up the virtual environment...
          python3.exe -m venv venv
          if errorlevel 1 (
              echo Failed to create virtual environment.
              exit /b 1
          )

      - name: Install dependencies
        shell: cmd
        run: |
          echo Installing dependencies...
          venv\Scripts\python.exe -m pip install --upgrade pip >nul 2>&1
          venv\Scripts\python.exe -m pip install -v -r requirements-windows.txt
          if errorlevel 1 (
              echo Failed to install dependencies.
              exit /b 1
          )

      - name: Install PyInstaller
        shell: cmd
        run: |
          echo Installing PyInstaller...
          venv\Scripts\python.exe -m pip install pyinstaller
          if errorlevel 1 (
              echo Failed to install PyInstaller.
              exit /b 1
          )

      - name: Create executable
        shell: cmd
        run: |
          echo Creating executable...
          venv\Scripts\python.exe -m PyInstaller --onefile --noconsole siracusa.py
          if errorlevel 1 (
              echo Failed to create executable.
              exit /b 1
          )

      - name: Upload venv as artifact
        uses: actions/upload-artifact@v4
        with:
          name: venv
          path: venv
          retention-days: 1

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: siracusa-executable
          path: dist/siracusa.exe
          retention-days: 1
